// <auto-generated />
using System;
using ApiMotoSync.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ApiMotoSync.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MotoSyncContext))]
    partial class MotoSyncContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMotoSync.Domain.Entities.Filial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("NVARCHAR2(160)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("FILIAIS", (string)null);
                });

            modelBuilder.Entity("ApiMotoSync.Domain.Entities.Moto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("FilialId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("GestorId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasDefaultValue("Disponível");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.HasIndex("GestorId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("MOTOS", (string)null);
                });

            modelBuilder.Entity("ApiMotoSync.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("NVARCHAR2(180)");

                    b.Property<Guid>("FilialId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FilialId");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("ApiMotoSync.Domain.Entities.Moto", b =>
                {
                    b.HasOne("ApiMotoSync.Domain.Entities.Filial", "Filial")
                        .WithMany("Motos")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMotoSync.Domain.Entities.Usuario", "Gestor")
                        .WithMany("MotosGerenciadas")
                        .HasForeignKey("GestorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Filial");

                    b.Navigation("Gestor");
                });

            modelBuilder.Entity("ApiMotoSync.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ApiMotoSync.Domain.Entities.Filial", "Filial")
                        .WithMany("Usuarios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("ApiMotoSync.Domain.Entities.Filial", b =>
                {
                    b.Navigation("Motos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ApiMotoSync.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("MotosGerenciadas");
                });
#pragma warning restore 612, 618
        }
    }
}
